// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNfjrzhk3gq6rqC-pLim7GeKwvtXkGq0',
    appId: '1:712493221599:web:695071715994801374cb6a',
    messagingSenderId: '712493221599',
    projectId: 'mindlog-b9e02',
    authDomain: 'mindlog-b9e02.firebaseapp.com',
    storageBucket: 'mindlog-b9e02.firebasestorage.app',
    measurementId: 'G-8PWFG7ZPSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpqeRuaHrvLq0sYilzMEEgDwfnuskWDg',
    appId: '1:712493221599:android:1c1567ae5b98097f74cb6a',
    messagingSenderId: '712493221599',
    projectId: 'mindlog-b9e02',
    storageBucket: 'mindlog-b9e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGfaAztfJXTnqkCCJxtoyIbkG4ntReM1I',
    appId: '1:712493221599:ios:5effb0610d9eaec774cb6a',
    messagingSenderId: '712493221599',
    projectId: 'mindlog-b9e02',
    storageBucket: 'mindlog-b9e02.firebasestorage.app',
    iosBundleId: 'com.example.mindlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGfaAztfJXTnqkCCJxtoyIbkG4ntReM1I',
    appId: '1:712493221599:ios:5effb0610d9eaec774cb6a',
    messagingSenderId: '712493221599',
    projectId: 'mindlog-b9e02',
    storageBucket: 'mindlog-b9e02.firebasestorage.app',
    iosBundleId: 'com.example.mindlog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNfjrzhk3gq6rqC-pLim7GeKwvtXkGq0',
    appId: '1:712493221599:web:f01d7a32c49b144d74cb6a',
    messagingSenderId: '712493221599',
    projectId: 'mindlog-b9e02',
    authDomain: 'mindlog-b9e02.firebaseapp.com',
    storageBucket: 'mindlog-b9e02.firebasestorage.app',
    measurementId: 'G-C78318VQBG',
  );
}
